function outFile = lifetimeSectionDriver(moduleFile, sectionTag, driverDir, driverName, substitutions)
%LIFETIMESECTIONDRIVER Write a driver script that replays one section of a module script.
%
%   outFile = lifetimeSectionDriver(moduleFile, sectionTag, driverDir, driverName, substitutions)
%
%   The FLIM module script `lifeTcalculationbernsen.m` is shipped unchanged with
%   this demo. It was written for one acquisition series: the folder the images
%   were exported to, the number of images per field of view, the fields of view
%   it loops over and the name of the output `.mat` file (asked for with a save
%   dialog) are all hard-coded in it. Both demo wrappers therefore replay the
%   section they need inside an isolated working copy, with those acquisition
%   settings replaced by the settings of the demo. Nothing else is touched, and
%   the generated driver is kept in the working copy so that it can be inspected.
%
%   Input
%     moduleFile    the shipped module script
%     sectionTag    regular expression matching the '%%' section header, e.g.
%                   '^%%\s*section\s*1'
%     driverDir     folder the generated driver is written to
%     driverName    file name of the generated driver
%     substitutions N x 3 cell array {pattern, replacement, expectedMatches}.
%                   Every line matching `pattern` is replaced by `replacement`;
%                   an error is raised when the number of matches differs from
%                   `expectedMatches`, so that a change in the module script can
%                   never silently disable a substitution.
%
%   Output
%     outFile       full path of the generated driver
%
%   Every substitution is echoed to the console, so the demo shows exactly which
%   lines were adapted.

if ~isfile(moduleFile)
    error('lifetimeSectionDriver:missingModule', 'Module script not found: %s', moduleFile);
end

lines = localReadLines(moduleFile);
sec   = localSectionLines(lines, sectionTag, moduleFile);

for k = 1:size(substitutions, 1)
    pat  = substitutions{k, 1};
    rep  = substitutions{k, 2};
    expN = substitutions{k, 3};

    idx = find(~cellfun(@isempty, regexp(sec, pat, 'once')));
    if numel(idx) ~= expN
        error('lifetimeSectionDriver:noMatch', ...
              'Expected %d line(s) matching "%s" in %s, found %d.', ...
              expN, pat, moduleFile, numel(idx));
    end
    for j = idx(:)'
        fprintf('    %-12s %s\n', 'replaced', localShorten(sec{j}));
        sec{j} = rep;
    end
end

header = { ...
    '% ---------------------------------------------------------------------------' ...
    '% GENERATED by the FLIM demo - do not edit.' ...
   ['% ' strrep(moduleFile, '\', '/')] ...
    '%' ...
    '% This is the section of the shipped module script, with the acquisition' ...
    '% settings replaced by the settings of the demo. See Readme.md.' ...
    '% ---------------------------------------------------------------------------' ...
    ''};

outFile = fullfile(driverDir, driverName);
fid = fopen(outFile, 'w', 'n');
if fid < 0
    error('lifetimeSectionDriver:cannotWrite', 'Cannot write %s.', outFile);
end
fprintf(fid, '%s\n', header{:});
fprintf(fid, '%s\n', sec{:});
fclose(fid);

fprintf('    %-12s %s\n', 'driver', driverName);
end

% ---------------------------------------------------------------------------

function lines = localReadLines(f)
txt   = fileread(f);
lines = regexp(txt, '\r\n|\n|\r', 'split');
if ~isempty(lines) && isempty(lines{end})
    lines(end) = [];
end
end

function sec = localSectionLines(lines, tag, moduleFile)
idx = find(~cellfun(@isempty, regexp(lines, tag, 'once')));
if numel(idx) ~= 1
    error('lifetimeSectionDriver:sectionNotFound', ...
          'Expected one section matching "%s" in %s, found %d.', tag, moduleFile, numel(idx));
end
start = idx(1);
nxt   = find(~cellfun(@isempty, regexp(lines(start+1:end), '^%%', 'once')));
if isempty(nxt)
    stop = numel(lines);
else
    stop = start + nxt(1) - 1;
end
sec = lines(start:stop);
end

function s = localShorten(s)
s = strtrim(s);
if numel(s) > 68
    s = [s(1:65) '...'];
end
end
